name: PanPhylo
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=3.9
  - biopython
  - scipy
  - matplotlib
  - numpy
  - pandas
  - seaborn=0.13.0
  - prodigal
  - diamond=0.9.14
  - mcl
  - mafft
  - hmmer
